name: psynthea-validation

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  - pandas
  - numpy
  - scipy
  - matplotlib

  - jupyter
  - ipykernel
  - pytest

  - pip

  - pip:
      - openpyxl