"""
Data loaders for synthetic patient cohorts.

This module is responsible for loading cohorts generated by different
simulation engines and converting them into the common ValidationCohort
representation used throughout the validation framework.

No validation, statistics or plotting logic should be implemented here.
"""

from pathlib import Path

import pandas as pd

from validation.constants import CSV_FILES, SOURCE_PSYNTHEA, SOURCE_SYNTHEA
from validation.models import ValidationCohort


def _read_csv(path: Path, required: bool = False) -> pd.DataFrame:
    """
    Read a CSV file if it exists.
    """

    if path.exists():
        return pd.read_csv(path)

    if required:
        raise FileNotFoundError(f"Required file not found: {path}")

    return pd.DataFrame()


def _load_cohort(
    output_path: str | Path,
    source: str,
) -> ValidationCohort:
    """
    Load canonical CSV tables into a ValidationCohort.
    """

    output_path = Path(output_path)

    return ValidationCohort(
        source=source,
        output_path=output_path,
        patients=_read_csv(
            output_path / CSV_FILES["patients"],
            required=True,
        ),
        encounters=_read_csv(
            output_path / CSV_FILES["encounters"]
        ),
        conditions=_read_csv(
            output_path / CSV_FILES["conditions"]
        ),
        medications=_read_csv(
            output_path / CSV_FILES["medications"]
        ),
        procedures=_read_csv(
            output_path / CSV_FILES["procedures"]
        ),
        observations=_read_csv(
            output_path / CSV_FILES["observations"]
        ),
    )


def load_psynthea(output_path: str | Path) -> ValidationCohort:
    """
    Load a cohort generated by psynthea.
    """

    return _load_cohort(
        output_path=output_path,
        source=SOURCE_PSYNTHEA,
    )


def load_synthea(output_path: str | Path) -> ValidationCohort:
    """
    Load a cohort generated by the original Java implementation of Synthea.
    """

    return _load_cohort(
        output_path=output_path,
        source=SOURCE_SYNTHEA,
    )
