"""
Data loaders for synthetic patient cohorts.

This module is responsible for loading cohorts generated by different
simulation engines (currently psynthea and Synthea Java) and converting
them into the common ValidationCohort representation used throughout
the validation framework.

No validation, statistics or plotting logic should be implemented here.
"""

from pathlib import Path

import pandas as pd

from validation.constants import CSV_FILES, SOURCE_PSYNTHEA, SOURCE_SYNTHEA
from validation.models import ValidationCohort


def _read_csv(path: Path, required: bool = False) -> pd.DataFrame:
    """
    Read a CSV file if it exists.

    Parameters
    ----------
    path
        Path to the CSV file.

    required
        If True, raise FileNotFoundError when the file does not exist.
        Otherwise return an empty DataFrame.

    Returns
    -------
    pandas.DataFrame
    """

    if path.exists():
        return pd.read_csv(path)

    if required:
        raise FileNotFoundError(f"Required file not found: {path}")

    return pd.DataFrame()


def load_psynthea(output_path: str | Path) -> ValidationCohort:
    """
    Load a cohort generated by psynthea.

    Parameters
    ----------
    output_path
        Folder containing the exported CSV files.

    Returns
    -------
    ValidationCohort
    """

    output_path = Path(output_path)

    return ValidationCohort(
        source=SOURCE_PSYNTHEA,
        output_path=output_path,
        patients=_read_csv(
            output_path / CSV_FILES["patients"],
            required=True,
        ),
        encounters=_read_csv(
            output_path / CSV_FILES["encounters"]
        ),
        conditions=_read_csv(
            output_path / CSV_FILES["conditions"]
        ),
        medications=_read_csv(
            output_path / CSV_FILES["medications"]
        ),
        observations=_read_csv(
            output_path / CSV_FILES["observations"]
        ),
    )


def load_synthea(output_path: str | Path) -> ValidationCohort:
    """
    Load a cohort generated by the original Java implementation of Synthea.

    Parameters
    ----------
    output_path
        Folder containing the exported CSV files.

    Returns
    -------
    ValidationCohort
    """

    output_path = Path(output_path)

    return ValidationCohort(
        source=SOURCE_SYNTHEA,
        output_path=output_path,
        patients=_read_csv(
            output_path / CSV_FILES["patients"],
            required=True,
        ),
        encounters=_read_csv(
            output_path / CSV_FILES["encounters"]
        ),
        conditions=_read_csv(
            output_path / CSV_FILES["conditions"]
        ),
        medications=_read_csv(
            output_path / CSV_FILES["medications"]
        ),
        observations=_read_csv(
            output_path / CSV_FILES["observations"]
        ),
    )