"""Stable public API for the scientific interpretation layer.

The interpretation package converts validation outputs into normalized evidence,
deterministic rule evaluations, research-safety summaries, actionable
recommendations and auditable reports.  Private implementation helpers remain in
submodules; supported consumers should import public symbols from here.
"""

from __future__ import annotations

from validation.interpretation.engine import (
    DEFAULT_INTERPRETATION_RULES,
    ENGINE_VERSION,
    EngineConfigurationError,
    EngineExecution,
    InterpretationEngine,
    InterpretationEngineConfig,
)
from validation.interpretation.evidence import (
    DEFAULT_EVIDENCE_REGISTRY,
    DuplicateEvidenceError,
    EvidenceAdapter,
    EvidenceBuilder,
    EvidenceCatalog,
    EvidenceExtractionError,
    EvidenceRegistry,
    FrameExtractionSpec,
    ScalarNormalization,
    collect_evidence,
    extract_dataframe_cell,
    extract_dataframe_rows,
    extract_scalar,
    normalize_scalar,
)
from validation.interpretation.models import (
    Confidence,
    EvidenceAvailability,
    EvidenceReference,
    EvidenceRole,
    EvidenceStrength,
    EvidenceValue,
    FindingStatus,
    InterpretationFinding,
    InterpretationReport,
    Recommendation,
    RecommendationPriority,
    RootCauseHypothesis,
    Severity,
)
from validation.interpretation.recommendations import (
    ActionPlanConfiguration,
    ActionPlanItem,
    RecommendationPlan,
    build_recommendation_plan,
)
from validation.interpretation.report import (
    InterpretationDocument,
    ReportConfiguration,
    ReportConsistencyError,
    build_interpretation_document,
    render_json_report,
    render_markdown_report,
    write_json_report,
    write_markdown_report,
    write_report_bundle,
)
from validation.interpretation.rules import (
    DEFAULT_CLINICAL_RULES,
    DEFAULT_EPIDEMIOLOGICAL_RULES,
    DEFAULT_SPANISH_ADAPTATION_RULES,
    DEFAULT_STATISTICAL_RULES,
    DEFAULT_STRUCTURAL_RULES,
    EpidemiologicalThresholds,
    InterpretationRule,
    PipelineStage,
    RuleEvaluation,
    RuleExecutionStatus,
    StageStatus,
    ValidationDimension,
)
from validation.interpretation.summary import (
    DimensionSummary,
    InterpretationSummary,
    SummaryConfiguration,
    build_interpretation_summary,
)
from validation.interpretation.workflow import (
    WORKFLOW_VERSION,
    InterpretationInput,
    InterpretationWorkflow,
    InterpretationWorkflowConfig,
    InterpretationWorkflowError,
    InterpretationWorkflowResult,
    WorkflowArtifacts,
)

__version__ = ENGINE_VERSION

__all__ = [
    "ActionPlanConfiguration",
    "ActionPlanItem",
    "Confidence",
    "DEFAULT_CLINICAL_RULES",
    "DEFAULT_EPIDEMIOLOGICAL_RULES",
    "DEFAULT_EVIDENCE_REGISTRY",
    "DEFAULT_INTERPRETATION_RULES",
    "DEFAULT_SPANISH_ADAPTATION_RULES",
    "DEFAULT_STATISTICAL_RULES",
    "DEFAULT_STRUCTURAL_RULES",
    "DimensionSummary",
    "DuplicateEvidenceError",
    "ENGINE_VERSION",
    "EngineConfigurationError",
    "EngineExecution",
    "EpidemiologicalThresholds",
    "EvidenceAdapter",
    "EvidenceAvailability",
    "EvidenceBuilder",
    "EvidenceCatalog",
    "EvidenceExtractionError",
    "EvidenceReference",
    "EvidenceRegistry",
    "EvidenceRole",
    "EvidenceStrength",
    "EvidenceValue",
    "FindingStatus",
    "FrameExtractionSpec",
    "InterpretationDocument",
    "InterpretationEngine",
    "InterpretationEngineConfig",
    "InterpretationFinding",
    "InterpretationInput",
    "InterpretationReport",
    "InterpretationRule",
    "InterpretationSummary",
    "InterpretationWorkflow",
    "InterpretationWorkflowConfig",
    "InterpretationWorkflowError",
    "InterpretationWorkflowResult",
    "PipelineStage",
    "Recommendation",
    "RecommendationPlan",
    "RecommendationPriority",
    "ReportConfiguration",
    "ReportConsistencyError",
    "RootCauseHypothesis",
    "RuleEvaluation",
    "RuleExecutionStatus",
    "ScalarNormalization",
    "Severity",
    "StageStatus",
    "SummaryConfiguration",
    "ValidationDimension",
    "WORKFLOW_VERSION",
    "WorkflowArtifacts",
    "__version__",
    "build_interpretation_document",
    "build_interpretation_summary",
    "build_recommendation_plan",
    "collect_evidence",
    "extract_dataframe_cell",
    "extract_dataframe_rows",
    "extract_scalar",
    "normalize_scalar",
    "render_json_report",
    "render_markdown_report",
    "write_json_report",
    "write_markdown_report",
    "write_report_bundle",
]