"""Public API for descriptive validation metrics.

The :mod:`validation.metrics` package provides the descriptive metric models
and calculators used to characterise synthetic cohorts generated by Synthea
Java and psynthea.

Metrics are organised into complementary domains:

- patient demographics;
- healthcare encounters;
- clinical conditions;
- medications;
- procedures;
- observations;
- data quality;
- cohort-level profiles.

Inferential hypothesis testing and cross-cohort statistical comparison belong
to :mod:`validation.comparison`.
"""

from __future__ import annotations

from .clinical import (
    ClinicalMetrics,
    DiseaseMetrics,
    calculate_clinical,
)
from .cohorts import (
    CohortCompletenessMetrics,
    CohortProfileMetrics,
    CohortTableCounts,
    calculate_cohort_profile,
)
from .demographics import (
    DemographicMetrics,
    calculate_demographics,
)
from .encounters import (
    EncounterMetrics,
    calculate_encounters,
)
from .medications import (
    MedicationMetrics,
    MedicationProfileMetrics,
    calculate_medications,
)
from .observations import (
    ObservationMetrics,
    ObservationProfileMetrics,
    calculate_observations,
)
from .procedures import (
    ProcedureMetrics,
    ProcedureProfileMetrics,
    calculate_procedures,
)
from .quality import (
    DataQualityMetrics,
    TableQualityMetrics,
    calculate_quality,
)

__all__ = [
    # Demographics.
    "DemographicMetrics",
    "calculate_demographics",

    # Healthcare utilisation.
    "EncounterMetrics",
    "calculate_encounters",

    # Clinical conditions.
    "DiseaseMetrics",
    "ClinicalMetrics",
    "calculate_clinical",

    # Medications.
    "MedicationMetrics",
    "MedicationProfileMetrics",
    "calculate_medications",

    # Procedures.
    "ProcedureMetrics",
    "ProcedureProfileMetrics",
    "calculate_procedures",

    # Observations.
    "ObservationMetrics",
    "ObservationProfileMetrics",
    "calculate_observations",

    # Data quality.
    "TableQualityMetrics",
    "DataQualityMetrics",
    "calculate_quality",

    # Cohort-level profiling.
    "CohortTableCounts",
    "CohortCompletenessMetrics",
    "CohortProfileMetrics",
    "calculate_cohort_profile",
]