"""Evidence-backed knowledge acquisition framework for validation Phase 2A.

The package exposes immutable scientific models, canonical taxonomies and
protocols, evidence-acquisition services, the validated knowledge registry and
explicit deterministic matching rules.  Importing this package performs no
I/O, protocol execution, causal inference or rule evaluation.
"""

from validation.knowledge.evidence import (
    ConcurrentEvidenceModificationError,
    DuplicateEvidenceError,
    EvidenceAcquisitionError,
    EvidenceCollection,
    EvidenceCollector,
    EvidenceCoverage,
    EvidenceProtocolMismatchError,
    EvidenceRequirementCoverage,
    EvidenceRequirementMismatchError,
    EvidenceSourceReader,
    FileEvidenceReader,
    MissingRequiredEvidenceError,
    ProtocolEvidenceAudit,
    attach_evidence,
    audit_protocol_evidence,
    canonical_json_bytes,
)
from validation.knowledge.models import (
    ActionPriority,
    CausalCertainty,
    CausalHypothesis,
    DetectionSignal,
    EvidenceDirection,
    EvidenceItem,
    EvidenceSourceKind,
    HypothesisEvidenceAssessment,
    HypothesisStatus,
    InvestigationCase,
    InvestigationStatus,
    KnowledgeEntry,
    KnowledgeEntryStatus,
    RecommendedAction,
    VerificationCheck,
    VerificationStatus,
)
from validation.knowledge.protocols import (
    CANONICAL_PROTOCOLS,
    EvidenceRequirement,
    EvidenceRequirementLevel,
    InvestigationProtocol,
    ProtocolCatalog,
    ProtocolStep,
    ProtocolStepKind,
    UnknownProtocolError,
)
from validation.knowledge.registry import (
    DuplicateInvestigationError,
    DuplicateKnowledgeEntryError,
    InvalidKnowledgePublicationError,
    KnowledgeRegistry,
    KnowledgeRegistryError,
    RegistrySnapshot,
    SupersessionError,
    UnknownInvestigationError,
    UnknownKnowledgeEntryError,
)
from validation.knowledge.rules import (
    DuplicateRuleError,
    InvalidRuleError,
    KnowledgeRule,
    RuleCatalog,
    RuleCondition,
    RuleMatch,
    RuleOperator,
    UnknownRuleError,
)
from validation.knowledge.taxonomy import (
    CANONICAL_TAXONOMY,
    RootCauseCategory,
    TaxonomyAxis,
    TaxonomyCatalog,
    TaxonomyTerm,
    UnknownTaxonomyTermError,
    ValidationDomain,
)

__all__ = [
    "ActionPriority",
    "CANONICAL_PROTOCOLS",
    "CANONICAL_TAXONOMY",
    "CausalCertainty",
    "CausalHypothesis",
    "ConcurrentEvidenceModificationError",
    "DetectionSignal",
    "DuplicateEvidenceError",
    "DuplicateInvestigationError",
    "DuplicateKnowledgeEntryError",
    "DuplicateRuleError",
    "EvidenceAcquisitionError",
    "EvidenceCollection",
    "EvidenceCollector",
    "EvidenceCoverage",
    "EvidenceDirection",
    "EvidenceItem",
    "EvidenceProtocolMismatchError",
    "EvidenceRequirement",
    "EvidenceRequirementCoverage",
    "EvidenceRequirementLevel",
    "EvidenceRequirementMismatchError",
    "EvidenceSourceKind",
    "EvidenceSourceReader",
    "FileEvidenceReader",
    "HypothesisEvidenceAssessment",
    "HypothesisStatus",
    "InvalidKnowledgePublicationError",
    "InvalidRuleError",
    "InvestigationCase",
    "InvestigationProtocol",
    "InvestigationStatus",
    "KnowledgeEntry",
    "KnowledgeEntryStatus",
    "KnowledgeRegistry",
    "KnowledgeRegistryError",
    "KnowledgeRule",
    "MissingRequiredEvidenceError",
    "ProtocolCatalog",
    "ProtocolEvidenceAudit",
    "ProtocolStep",
    "ProtocolStepKind",
    "RecommendedAction",
    "RegistrySnapshot",
    "RootCauseCategory",
    "RuleCatalog",
    "RuleCondition",
    "RuleMatch",
    "RuleOperator",
    "SupersessionError",
    "TaxonomyAxis",
    "TaxonomyCatalog",
    "TaxonomyTerm",
    "UnknownInvestigationError",
    "UnknownKnowledgeEntryError",
    "UnknownProtocolError",
    "UnknownRuleError",
    "UnknownTaxonomyTermError",
    "ValidationDomain",
    "VerificationCheck",
    "VerificationStatus",
    "attach_evidence",
    "audit_protocol_evidence",
    "canonical_json_bytes",
]